// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh18Nm86wRSY4XmlwI6vapfgF9YivPFak',
    appId: '1:1009069069710:web:f1498b6629c72e933940df',
    messagingSenderId: '1009069069710',
    projectId: 'pawskills-3c9fa',
    authDomain: 'pawskills-3c9fa.firebaseapp.com',
    databaseURL: 'https://pawskills-3c9fa-default-rtdb.firebaseio.com',
    storageBucket: 'pawskills-3c9fa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuWDyGOV1lCvm5NoO7_ju-29HU5vf3iWU',
    appId: '1:1009069069710:android:01e4846c380749c83940df',
    messagingSenderId: '1009069069710',
    projectId: 'pawskills-3c9fa',
    databaseURL: 'https://pawskills-3c9fa-default-rtdb.firebaseio.com',
    storageBucket: 'pawskills-3c9fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArXX2rDfXJBE25_SphuAs2UNk_H8siVAk',
    appId: '1:1009069069710:ios:8cebb9046aa5dfaa3940df',
    messagingSenderId: '1009069069710',
    projectId: 'pawskills-3c9fa',
    databaseURL: 'https://pawskills-3c9fa-default-rtdb.firebaseio.com',
    storageBucket: 'pawskills-3c9fa.appspot.com',
    iosBundleId: 'com.example.pawskills',
  );
}
